source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StrongestPasswordValidator_Example' do
pod "StrongestPasswordValidator", :path => "../"
end

target 'StrongestPasswordValidator_Tests' do
pod "StrongestPasswordValidator", :path => "../"

pod 'Specta'
pod 'Expecta'
pod 'FBSnapshotTestCase'
pod 'Expecta+Snapshots'
end
